### ISSUE TITLE
Has the public release of layer been closed?

### ISSUE THREAD

**Issue by sumiden** [PDAL/lambda#11]
I could not add layer to lambda.
Let me know if there is a better way.

> You are not authorized to perform: lambda:GetLayerVersion.

And AWS-CLI also error.
`aws lambda get-layer-version-by-arn --arn arn:aws:lambda:us-east-1:163188234892:layer:pdal:41`

> An error occurred (AccessDeniedException) when calling the GetLayerVersionByArn operation: User: arn:aws:iam::963080800244:root is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:us-east-1:163188234892:layer:pdal:41 because no resource-based policy allows the lambda:GetLayerVersion action

**Comment by hobu** [comment]
This project is defunct. It is no longer necessary now that you can create Lambda images with Docker. Just use that instead.

**Comment by sumiden** [comment]
Thank you for your quick response. I will try using docker.
But, I am not familiar with docker. Is the following procedure correct?

https://aws.amazon.com/premiumsupport/knowledge-center/lambda-layer-simulated-docker/?nc1=h_ls

In this case, I have no idea how to make requirements.txt. 
I think PDAL cannot install with pip command.

**Comment by hobu** [comment]
This venue is not the appropriate place for support questions about AWS deployment.
