### ISSUE TITLE
Deploy PDAL Lambda Layer to AWS us-west-2

### ISSUE THREAD

**Issue by keythread** [PDAL/lambda#2]
Lambda Layers can't be shared across regions. Would like to see this pushed to us-west-2 for USGS access.

**Comment by hobu** [comment]
`arn:aws:lambda:us-west-2:163178234892:layer:pdal`

**Comment by bernardiego** [comment]
Hello! I tried this (us-west-2) layer in my nodejs 10.x lambda function and an error was thrown:

"Error: ogr2ogr: error while loading shared libraries: libsqlite3.so.0: cannot open shared object file: No such file or directory".

I'm just trying to use ogr2ogr tool. What could the problem be?
Thank you in advance,

**Comment by hobu** [comment]
https://github.com/hobu/usgs-lidar/blob/master/lambda/lambda_function.py shows some example use of the lambda layer.
