### ISSUE TITLE
Availability in eu-west-1

### ISSUE THREAD

**Issue by ChristopheBougere** [PDAL/lambda#4]
Hi, I am getting this error when trying to add `arn:aws:lambda:eu-west-1:163178234892:layer:pdal:15` in eu-west-1:
`You are not authorized to perform: lambda:GetLayerVersion.`
I guessed from #2 that layers were available in all regions am I right?
Also, how should I infer the layer version? Are the identical across regions?
Thanks

**Comment by hobu** [comment]
It is only available in us-east-1. You'll have to build a copy of it yourself if you need it in another region.

**Comment by ChristopheBougere** [comment]
OK I see, thanks for your awesome responsiveness 👌
