### ISSUE TITLE
Using gdaltools

### ISSUE THREAD

**Issue by mebibou** [PDAL/lambda#5]
Can this be used to import `gdaltools` to convert some files? in my lambda python function I am doing:

```python
import gdaltools

ogr = gdaltools.ogr2ogr()
ogr.set_encoding('UTF-8')
ogr.set_input(input_file, srs='EPSG:4326')
ogr.set_output(output_file)
ogr.execute()
```

which throws on execution
```
[Errno 2] No such file or directory: '/usr/bin/ogr2ogr': '/usr/bin/ogr2ogr'
```

I've also tried to set `os.environ['GDAL_DATA'] = '/opt/share/gdal'` as seen [here](https://github.com/hobu/usgs-lidar/blob/master/lambda/lambda_function.py#L18) but to no avail

**Comment by hobu** [comment]
I think the issue is the compiled PREFIX for GDAL was `/usr/`, but when it is deployed to a Lambda, it's prefix is actually `/var/task`. If you put `/var/task/bin` on your PATH, maybe the gdaltools library will find it.

**Comment by mebibou** [comment]
@hobu so I tried to set `PATH` to `/usr/local/bin:/usr/bin/:/bin:/opt/bin:/var/task/bin` in the function `Environment variables` taking https://docs.aws.amazon.com/lambda/latest/dg/lambda-environment-variables.html as default value, but still complaining about `/usr/bin/ogr2ogr`

**Comment by mebibou** [comment]
I'm actually new to Lambda and trying to migrate a Dockerized library to lambda so maybe there is a simple way to fix this, like creating a symlink?

**Comment by hobu** [comment]
Is there a setting in `gdaltools` that allows you to override the GDAL_BIN path? You need something like that.

**Comment by SimonsUnikaNamn** [comment]
I think https://github.com/PDAL/lambda/issues/7 is related,
when using lambda layers the code is put in the /opt folder https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html
But when we build the whole package we have /usr as prefix https://github.com/PDAL/lambda/blob/master/Dockerfile#L13

I am trying to build with using /opt as prefix and will see if that works
