### ISSUE TITLE
publish docker image to docker hub

### ISSUE THREAD

**Issue by vincentsarago** [PDAL/lambda#6]
👋, first thanks for making this layer public, it is really helpful. 

I need to add rasterio to my lambda package but when using rasterio wheels the package exceed the size limit (additional size between PDAL Layer and my package) because of the duplicate of GDAL libs I guess. To make it pass I need to build my package using the exact docker image you used for the layer (so the rasterio module is compiled using the gdal libs).

I guess I might not be the only one in this case so it might be useful to push the docker image to docker hub.

Thanks.

**Comment by hobu** [comment]
I had been hesitant to make the docker images available because I was worried about them getting stale. The lambda layers also stale pretty quickly. My assumption was anyone using this who wanted to do real work with them would customize and build themselves. You're breaking that assumption 😉 

Is there a way to make rasterio do a non-wheel install? I don't know much about the mandelbrot of packaging possibilities in Python anymore.

**Comment by vincentsarago** [comment]
thanks @hobu 
In fact after some quick test I had to build my own docker with pdal because of path/lib issues (still WIP, I'll try to make the repo public when it's done). 

> Is there a way to make rasterio do a non-wheel install? I don't know much about the mandelbrot of packaging possibilities in Python anymore.

yes you just need to have `GDAL_CONFIG` and `PROJ_LIB` env set and do `pip install --no-binary rasterio`

**Comment by hobu** [comment]
If you provide a PR that adds rasterio/shapely/fiona I'd happily merge and repush the layer.

**Comment by vincentsarago** [comment]
To be honest, I think it's better to add those as separate layers. I could add some documentation to explain how to create such a layer/package

**Comment by hobu** [comment]
My instinct is they're small and you only get 5 layers total, but I don't have a strong opinion. I wish AWS would relax the size limit a little bit. 50mb is really tough.

**Comment by vincentsarago** [comment]
zip can be up to 100Mb and when unzipped it can be up to 250Mb If I recall. Right now the `pdal` layer weight 18Mb (52Mb) which is great

**Comment by vincentsarago** [comment]
@hobu almost unrelated question, do you know the latest version of the layer on AWS ?

**Comment by hobu** [comment]
`arn:aws:lambda:us-east-1:163178234892:layer:pdal:15`

**Comment by vincentsarago** [comment]
FYI, this is how I create a package with rasterio using the `pdal/lambda` image 

```Dockerfile
FROM lambda:pdal

ENV \
  LANG=en_US.UTF-8 \
  LC_ALL=en_US.UTF-8 \
  CFLAGS="--std=c99"

RUN \
    pip3.7 install pip -U \
    && pip3.7 install cython numpy --no-binary numpy

ENV PACKAGE_PREFIX=/tmp/package

################################################################################
#                            CREATE PACKAGE                                    #
################################################################################

RUN pip3.7 install --no-binary rasterio,numpy -t $PACKAGE_PREFIX
COPY handler.py $PACKAGE_PREFIX/handler.py

RUN cd $PACKAGE_PREFIX && zip -r9q /tmp/package.zip *
```

**Comment by hobu** [comment]
FYI, I have pushed a `pdal/lambda` container to DockerHub to support these kinds of activities.
