### ISSUE TITLE
Cannot find proj.db

### ISSUE THREAD

**Issue by SimonsUnikaNamn** [PDAL/lambda#7]
Thank you for an awesome lambda layer.

I am having issues running the `pdal pipeline` command.

```
bash-4.2# pdal pipeline totiff.json
(pdal pipeline Error) GDAL failure (1) PROJ: proj_create_from_database: Cannot find proj.db
PDAL: Could not import coordinate system 'EPSG:5845': PROJ: proj_create_from_database: Cannot find proj.db.
```

When running an strace it seems like it is trying to find the file in /usr/share
```
open("/usr/share/proj/proj.db", O_RDONLY) = -1 ENOENT (No such file or directory)
```

While the file actually is located in 
```
/opt/share/proj/proj.db
```

I wonder if it is because when building we are using the /usr as a prefix?

**Comment by hobu** [comment]
> I wonder if it is because when building we are using the /usr as a prefix?

Yes. You currently have to explicitly set `PROJ_LIB` and `GDAL_DATA` to use this lambda layer.

**Comment by SimonsUnikaNamn** [comment]
I see, wonderful 👏
